version: '3'

services:

  pg-database:
    image: postgres:latest
    environment:
      POSTGRES_USER: bran
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  goapp:
    build: .
    environment:
      POSTGRES_USER: bran
      POSTGRES_PASSWORD: password
    links:
      - pg-database
    ports:
      - 8080:8080
